meta_product_name: "Olibre"
meta_title: "Olibre - Toute la natation en eau libre près de chez toi"
meta_description: "Olibre te permet de rechercher et créer des évènements de natation en eau libre en France."
meta_image: "eaulibre.png" # should exist in `app/assets/images/`
